export const INBODY_FIELDS = [
  // ── Composition globale ──────────────────────────────────────────────────
  {
    key: 'weight_kg',
    label: 'Poids',
    unit: 'kg',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: true,
    higherIsBetter: null,
    normalRange: null,
  },
  {
    key: 'skeletal_muscle_mass_kg',
    label: 'Masse musculaire squelettique',
    shortLabel: 'Masse musc.',
    unit: 'kg',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: true,
    higherIsBetter: true,
    normalRange: null,
  },
  {
    key: 'body_fat_mass_kg',
    label: 'Masse grasse',
    shortLabel: 'Masse grasse',
    unit: 'kg',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: true,
    higherIsBetter: false,
    normalRange: null,
  },
  {
    key: 'body_fat_percent',
    label: 'Taux de graisse corporelle',
    shortLabel: 'BF %',
    unit: '%',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: true,
    higherIsBetter: false,
    normalRange: { min: 10, max: 20 },
  },
  {
    key: 'lean_body_mass_kg',
    label: 'Masse maigre',
    unit: 'kg',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
  },
  {
    key: 'fat_free_mass_kg',
    label: 'Masse non grasse',
    unit: 'kg',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
  },
  {
    key: 'bmi',
    label: 'IMC',
    unit: 'kg/m²',
    category: 'composition',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: false,
    higherIsBetter: null,
    normalRange: { min: 18.5, max: 25 },
  },
  {
    key: 'height_cm',
    label: 'Taille',
    unit: 'cm',
    category: 'composition',
    decimals: 1,
    inputStep: 0.5,
    showInSummary: false,
    higherIsBetter: null,
    normalRange: null,
  },

  // ── Analyse segmentaire ──────────────────────────────────────────────────
  {
    key: 'segmental_lean_right_arm_kg',
    label: 'Bras droit (masse maigre)',
    shortLabel: 'Bras D',
    unit: 'kg',
    category: 'segmental',
    decimals: 2,
    inputStep: 0.01,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
    segment: 'right_arm',
  },
  {
    key: 'segmental_lean_left_arm_kg',
    label: 'Bras gauche (masse maigre)',
    shortLabel: 'Bras G',
    unit: 'kg',
    category: 'segmental',
    decimals: 2,
    inputStep: 0.01,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
    segment: 'left_arm',
  },
  {
    key: 'segmental_lean_trunk_kg',
    label: 'Tronc (masse maigre)',
    shortLabel: 'Tronc',
    unit: 'kg',
    category: 'segmental',
    decimals: 2,
    inputStep: 0.01,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
    segment: 'trunk',
  },
  {
    key: 'segmental_lean_right_leg_kg',
    label: 'Jambe droite (masse maigre)',
    shortLabel: 'Jambe D',
    unit: 'kg',
    category: 'segmental',
    decimals: 2,
    inputStep: 0.01,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
    segment: 'right_leg',
  },
  {
    key: 'segmental_lean_left_leg_kg',
    label: 'Jambe gauche (masse maigre)',
    shortLabel: 'Jambe G',
    unit: 'kg',
    category: 'segmental',
    decimals: 2,
    inputStep: 0.01,
    showInSummary: false,
    higherIsBetter: true,
    normalRange: null,
    segment: 'left_leg',
  },

  // ── Eau corporelle ───────────────────────────────────────────────────────
  {
    key: 'total_body_water_l',
    label: 'Eau corporelle totale',
    shortLabel: 'ECT',
    unit: 'L',
    category: 'water',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: false,
    higherIsBetter: null,
    normalRange: null,
  },
  {
    key: 'intracellular_water_l',
    label: 'Eau intracellulaire',
    shortLabel: 'EIC',
    unit: 'L',
    category: 'water',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: false,
    higherIsBetter: null,
    normalRange: null,
  },
  {
    key: 'extracellular_water_l',
    label: 'Eau extracellulaire',
    shortLabel: 'EEC',
    unit: 'L',
    category: 'water',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: false,
    higherIsBetter: null,
    normalRange: null,
  },
  {
    key: 'ecw_tbw_ratio',
    label: 'Ratio EEC/ECT',
    shortLabel: 'EEC/ECT',
    unit: '',
    category: 'water',
    decimals: 3,
    inputStep: 0.001,
    showInSummary: false,
    higherIsBetter: false,
    normalRange: { min: 0.360, max: 0.390 },
  },

  // ── Métabolisme & morpho ─────────────────────────────────────────────────
  {
    key: 'basal_metabolic_rate_kcal',
    label: 'Métabolisme de base',
    shortLabel: 'BMR',
    unit: 'kcal',
    category: 'metabolism',
    decimals: 0,
    inputStep: 1,
    showInSummary: false,
    higherIsBetter: null,
    normalRange: null,
  },
  {
    key: 'waist_cm',
    label: 'Tour de taille',
    unit: 'cm',
    category: 'metabolism',
    decimals: 1,
    inputStep: 0.5,
    showInSummary: false,
    higherIsBetter: false,
    normalRange: { min: 70, max: 94 },
  },
  {
    key: 'waist_hip_ratio',
    label: 'Ratio taille/hanches',
    shortLabel: 'WHR',
    unit: '',
    category: 'metabolism',
    decimals: 2,
    inputStep: 0.01,
    showInSummary: false,
    higherIsBetter: false,
    normalRange: { min: 0.85, max: 1.0 },
  },
  {
    key: 'visceral_fat_area_cm2',
    label: 'Surface de graisse viscérale',
    shortLabel: 'Graisse visc.',
    unit: 'cm²',
    category: 'metabolism',
    decimals: 1,
    inputStep: 0.5,
    showInSummary: false,
    higherIsBetter: false,
    normalRange: { min: 0, max: 100 },
  },

  // ── Qualité cellulaire ───────────────────────────────────────────────────
  {
    key: 'phase_angle_deg',
    label: 'Angle de phase',
    shortLabel: 'Angle phase',
    unit: '°',
    category: 'cellular',
    decimals: 1,
    inputStep: 0.1,
    showInSummary: true,
    higherIsBetter: true,
    normalRange: { min: 6.0, max: 8.5 },
  },
]

export const INBODY_CATEGORIES = {
  composition: { label: 'Composition globale',   order: 1 },
  segmental:   { label: 'Analyse segmentaire',   order: 2 },
  water:       { label: 'Eau corporelle',         order: 3 },
  metabolism:  { label: 'Métabolisme & morpho',   order: 4 },
  cellular:    { label: 'Qualité cellulaire',     order: 5 },
}

export function getFieldsByCategory() {
  const result = {}
  for (const [cat, meta] of Object.entries(INBODY_CATEGORIES)) {
    result[cat] = { ...meta, fields: INBODY_FIELDS.filter(f => f.category === cat) }
  }
  return result
}

export function getField(key) {
  return INBODY_FIELDS.find(f => f.key === key) ?? null
}

export const SUMMARY_FIELDS = INBODY_FIELDS.filter(f => f.showInSummary)
