name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push image frontend
        run: |
          docker build \
            --no-cache \
            -t ghcr.io/matteo-nossro/hevy-viz-frontend:latest \
            ./frontend
          docker push ghcr.io/matteo-nossro/hevy-viz-frontend:latest

      - name: Deploy via Portainer API
        run: |
          STACK_ID=$(curl -s \
            -H "X-API-Key: ${{ secrets.PORTAINER_TOKEN }}" \
            ${{ secrets.PORTAINER_URL }}/api/stacks | \
            jq -r '.[] | select(.Name=="hevy-viz") | .Id')

          curl -sk -X POST \
            -H "X-API-Key: ${{ secrets.PORTAINER_TOKEN }}" \
            "${{ secrets.PORTAINER_URL }}/api/stacks/$STACK_ID/images/pull?endpointId=1"

          curl -sk -X PUT \
            -H "X-API-Key: ${{ secrets.PORTAINER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"pullImage": true, "prune": false}' \
            "${{ secrets.PORTAINER_URL }}/api/stacks/$STACK_ID?endpointId=1"

      - name: Nettoyage
        if: always()
        run: docker image prune -f
